blockchain_analyst:
  supported_networks:
  - ethereum
  - solana
  - avalanche
  - polygon
crypto_economics:
  defi_protocols_to_track:
  - uniswap
  - aave
  - curve
  - compound
default_agents:
- all
enable_agent_affinity: true
fintech_navigator:
  news_sources:
  - bloomberg
  - reuters
  - coindesk
logging:
  file: finchain.log
  level: INFO
ml_investment_strategist:
  risk_profiles:
  - conservative
  - moderate
  - aggressive
regulatory_compliance:
  jurisdictions_to_track:
  - us
  - eu
  - uk
  - sg
  - in
use_nlp: true
